name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ed6095-web
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Push snake
        uses: EndBug/add-and-commit@v9
        with:
          branch: output
          message: "Generate contribution snake"
          add: "dist/*.svg"
